<a href="https://colab.research.google.com/github/anish102/pytorch_ml_learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [11]:
# scalar
SCALAR = torch.tensor(7)
SCALAR, SCALAR.ndim, SCALAR.item()

(tensor(7), 0, 7)

In [12]:
# vector
VECTOR = torch.tensor([7,7])
VECTOR, VECTOR.ndim, VECTOR.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [13]:
# matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX, MATRIX.ndim, MATRIX.shape, MATRIX[1]

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]),
 tensor([ 9, 10]))

In [16]:
# tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))