<a href="https://colab.research.google.com/github/anish102/pytorch_ml_learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [16]:
# scalar
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.item()

(tensor(7), 0, 7)

In [17]:
# vector
vector = torch.tensor([7,7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [18]:
# matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX, MATRIX.ndim, MATRIX.shape, MATRIX[1]

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]),
 tensor([ 9, 10]))

In [19]:
# tensor
TENSOR = torch.tensor([
    [
        [
            [  12,   -3,  587],
            [  44, 1024,   19],
            [  -7,   18,   91]
        ],
        [
            [  99,   51,  -42],
            [   3,  -17, 2048],
            [ 111,    0,  -13]
        ],
    ],
    [
        [
            [ -88,  233,   10],
            [ 512,  -64,   77],
            [  29,   31, -999]
        ],
        [
            [ 1_000,    5,   -6],
            [   73,  888,   12],
            [  -50,   14,  256]
        ]
    ]
])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[[  12,   -3,  587],
           [  44, 1024,   19],
           [  -7,   18,   91]],
 
          [[  99,   51,  -42],
           [   3,  -17, 2048],
           [ 111,    0,  -13]]],
 
 
         [[[ -88,  233,   10],
           [ 512,  -64,   77],
           [  29,   31, -999]],
 
          [[1000,    5,   -6],
           [  73,  888,   12],
           [ -50,   14,  256]]]]),
 4,
 torch.Size([2, 2, 3, 3]))

In [20]:
# random tensors
random_tensor = torch.rand(1,2,3,4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[[[0.3378, 0.5883, 0.4500, 0.0254],
           [0.0815, 0.6390, 0.4727, 0.1562],
           [0.3734, 0.7336, 0.0873, 0.4857]],
 
          [[0.0768, 0.8085, 0.2521, 0.4076],
           [0.8738, 0.1225, 0.7119, 0.5086],
           [0.9472, 0.9603, 0.4148, 0.2859]]]]),
 4,
 torch.Size([1, 2, 3, 4]))

In [21]:
# random tensor similar to image tensors
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
# tensors with zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
# tensors with ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)